name: Deploy Jackpot to brianmaiyo.dev Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H brianmaiyo.dev >> ~/.ssh/known_hosts

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Deploy to Linux Apache server
        run: |
          ssh -o StrictHostKeyChecking=no maiyo@brianmaiyo.dev << 'EOF'
            cd /var/www/Jackpot/
            git pull origin main
            cd frontend
            npm install
            npm run build
            pm2 restart jackpot-fronted
            pm2 restart jackpot-backend
          EOF
