name: Deploy Jackpot to brianmaiyo.dev Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H brianmaiyo.dev >> ~/.ssh/known_hosts

      - name: Start SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no maiyo@brianmaiyo.dev << 'EOF'
            set -e  # fail fast if any command fails

            echo "▶ Pulling latest code..."
            cd /var/www/Jackpot/
            git pull origin main

            echo "▶ Installing frontend dependencies and building..."
            cd frontend
            npm install
            npm run build

            echo "▶ Restarting frontend and backend apps..."
            pm2 restart jackpot-fronted
            pm2 restart jackpot-backend

            echo "✅ Deployment complete."
          EOF
